In [12]:
import numpy as np

In [13]:
class TicTacToe:
    def __init__(self):
        self.row_count = 3
        self.column_count = 3
        self.action_size = self.row_count * self.column_count
        
    def get_initial_state(self):
        return np.zeros((self.row_count, self.column_count))
    
    def get_next_state(self, state, action, player):
        row = action // self.column_count
        col = action % self.column_count
        state[row, col] = player
        return state
    
    def get_valid_moves(self, state):
        return (state.reshape(-1) == 0).astype(np.uint8)
    
    def check_win(self, state, action):
        row = action // self.column_count
        col = action % self.column_count
        player = state[row, col]
        
        connect = player * self.column_count # we'll just use column_count here for all instead of row_count as it is the same
        
        return (
            np.sum(state[row, :]) == connect
            or np.sum(state[:, col]) == connect
            or np.sum(np.diag(state)) == connect
            or np.sum(np.diag(np.flip(state, axis=0))) == connect
        )
    
    def get_value_and_terminated(self, state, action):
        if self.check_win(state, action):
            return 1, True
        if np.sum(self.get_valid_moves(state)) == 0:
            return 0, True
        return 0, False
    
    def get_opponent(self, player):
        return -player
            

In [14]:
tictactoe = TicTacToe()
player = 1

state = tictactoe.get_initial_state()

while True:
    print(state)
    valid_moves = tictactoe.get_valid_moves(state)
    print("valid_moves", [i for i in range(tictactoe.action_size) if valid_moves[i] == 1])
    action = int(input(f"{player}:"))
    
    if not valid_moves[action]:
        print(f"action {action} not valid")
        continue
    
    state = tictactoe.get_next_state(state, action, player)
    
    value, is_terminal = tictactoe.get_value_and_terminated(state, action)
    
    if is_terminal:
        print(state)
        if value == 1:
            print(player, "won")
        else:
            print("draw")
        break
    
    player = tictactoe.get_opponent(player)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
valid_moves [0, 1, 2, 3, 4, 5, 6, 7, 8]
[[0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
valid_moves [0, 2, 3, 4, 5, 6, 7, 8]
[[ 0.  1. -1.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
valid_moves [0, 3, 4, 5, 6, 7, 8]
[[ 0.  1. -1.]
 [ 1.  0.  0.]
 [ 0.  0.  0.]]
valid_moves [0, 4, 5, 6, 7, 8]
[[ 0.  1. -1.]
 [ 1. -1.  0.]
 [ 0.  0.  0.]]
valid_moves [0, 5, 6, 7, 8]
[[ 0.  1. -1.]
 [ 1. -1.  1.]
 [ 0.  0.  0.]]
valid_moves [0, 6, 7, 8]
[[ 0.  1. -1.]
 [ 1. -1.  1.]
 [-1.  0.  0.]]
-1 won
